### PR TITLE
WebKit issues on Apple devices: Urgently (needs fixing for future iOS versions)

### PR DESCRIPTION
**Pull request by eqMFqfFd**
**WebKit** issues on *Apple* devices (tested on iPads with iOS 10), refreshing pages and problems selecting text on some sites (Tested on net2ftp.com & GitHub wiki editing when copying and pasting). **WebKit** errors are returned and "an error has occurred several times in -*the site*-". The problem also affects device apps, causing crashes even in the Settings *Apple* app. The keyboard is slow to respond in addition. The problem doesn't happen anymore when restoring all the iPad, but comes back when you start selecting text to copy, paste..

#### Interesting
- Issue doesn't happen in plain text pages (.txt) or any other extension that doesn't load HTML content.
- Issue is not solved even restarting the device tons of times.

#### Info
- Only tested in iPads; iPad 3 & iPad Pro.

### CODE REVIEW

**Comment by dpogue** [comment]
WebKit isn't developed on GitHub (this is a read-only mirror), so the WebKit developers are unlikely to see this.

Please file a bug against WebKit at https://bugs.webkit.org/ and against iOS at https://bugreport.apple.com/

**Comment by rniwa** [comment]
Please report this problem to Apple instead: https://developer.apple.com/bug-reporting/

**Comment by rniwa** [comment]
Closing.

**Comment by eqMFqfFd** [comment]
Took a while to answer...
Was the issue fixed anyways? It didn't occur me anymore since some iOS update, that is, I still present browsing issues in certain webpages sometimes, but that seems to be a normal occurrence. What is worrying is that if it happens again it can really cause a bad moment to the person who has it, and it did to me. I had to go to technical service and they (forcefully) restored the device, their response was a "software issue".

**Comment by rniwa** [comment]
We had a number of issues in service worker and cache that had since addressed. Since there is no detailed reproducible test case attached, I can't tell you which one of the existing bugs you were encountering but such a bug report & discussion really needs to happen on https://bugs.webkit.org and/or https://feedbackassistant.apple.com/welcome, not on a Github PR.

**Pull request closed without merging**
